# Generated by Django 4.0.1 on 2022-01-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='purchas_price',
            field=models.IntegerField(blank=True, default=100000),
        ),
    ]
