# Generated by Django 4.0.1 on 2022-01-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_rating_purchas_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='purchas_price',
            new_name='purchase_price',
        ),
    ]
