# Generated by Django 4.0.1 on 2022-01-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_rename_purchas_price_rating_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.extraquestion'),
        ),
    ]
